### ISSUE TITLE
Heroku timezone and config/application.rb

### ISSUE THREAD

**Issue by stephaniewilkinson** [stephaniewilkinson/macros#1]
I have a progress bar that represents hours gone by as a percentage of 24 hours. But on heroku right now (3:30pm) shows up as the day being 91% over, whereas on my local instance the day is only 62% percent over.

```ruby
<h3 class='inline'>Time</h3>
<h5 class='inline'> &nbsp; percentage of 24 hours</h5>
<div class="progress">
  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="<%= (Time.now.hour)*100/24 %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= (Time.now.hour)*100/24 %>%;">
    <%= (Time.now.hour)*100/24 %>%
  </div>
</div>
```
I have my local time set to Pacific in my initializer. 

```ruby
module Macros
  class Application < Rails::Application
    config.time_zone = 'Pacific Time (US & Canada)'
  end
end
```

Why wouldn't heroku be updating to my local timezone when I deploy? Unless I'm wrong and that's not the problem?

### What heroku looks like
<img width="1279" alt="screen shot 2016-06-08 at 3 26 36 pm" src="https://cloud.githubusercontent.com/assets/2397260/15913014/a64cd694-2d8c-11e6-9466-1a3628822c5c.png">

### What my local instance looks like 
<img width="1280" alt="screen shot 2016-06-08 at 3 26 28 pm" src="https://cloud.githubusercontent.com/assets/2397260/15913017/a7c206c0-2d8c-11e6-8d23-d55907d58a7e.png">

**Comment by stephaniewilkinson** [comment]
```
2016-06-08T22:23:27.914619+00:00 app[web.1]:   SQL (0.9ms)  INSERT INTO "users" ("name", "email", "password_digest", "carbs_goal", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["name", "Kathy wilkinson"], ["email", "Wilkinson.Kathy.E@gmail.com"], ["password_digest", "$2a$10$ldlOGgYOdxxc8p6VIXDuiOEbc8KzmkYJevW.3.ny34GmQkXih6yA6"], ["carbs_goal", 100], ["created_at", "2016-06-08 22:23:27.911230"], ["updated_at", "2016-06-08 22:23:27.911230"]]
2016-06-08T22:23:27.917201+00:00 app[web.1]: Redirected to http://masteryourmacros.herokuapp.com/
2016-06-08T22:23:27.828519+00:00 app[web.1]: Started POST "/users" for 100.9.117.185 at 2016-06-08 22:23:27 +0000
2016-06-08T22:23:27.830771+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"lluGQBT6KbmJlymyNzo54th9g4YwcYEMU4FNJKWzWkC6NTXgcJ2fJBdvyHFoXCW7TPtD03xuXy8+RdIE7Ojsfw==", "user"=>{"name"=>"Kathy wilkinson", "carbs_goal"=>"100", "fat_goal"=>"", "protein_goal"=>"", "email"=>"Wilkinson.Kathy.E@gmail.com", "password"=>"[FILTERED]"}, "commit"=>"Sign Up"}
2016-06-08T22:23:28.035974+00:00 app[web.1]: Completed 500 Internal Server Error in 6ms (ActiveRecord: 2.7ms)
2016-06-08T22:23:28.037324+00:00 app[web.1]: 
2016-06-08T22:23:28.037334+00:00 app[web.1]:   app/controllers/staticpages_controller.rb:13:in `/'
2016-06-08T22:23:28.037335+00:00 app[web.1]: 
2016-06-08T22:23:28.037336+00:00 app[web.1]: 
2016-06-08T22:23:28.037332+00:00 app[web.1]: TypeError (nil can't be coerced into Fixnum):
2016-06-08T22:23:28.033019+00:00 app[web.1]:   User Load (1.9ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 7]]
2016-06-08T22:23:28.035153+00:00 app[web.1]:   Food Load (0.9ms)  SELECT "foods".* FROM "foods" WHERE "foods"."user_id" = $1  [["user_id", 7]]
2016-06-08T22:23:28.037334+00:00 app[web.1]:   app/controllers/staticpages_controller.rb:13:in `index'
2016-06-08T22:23:28.028009+00:00 app[web.1]: Started GET "/" for 100.9.117.185 at 2016-06-08 22:23:28 +0000
2016-06-08T22:23:27.921117+00:00 heroku[router]: at=info method=POST path="/users" host=masteryourmacros.herokuapp.com request_id=2628b12a-599a-4127-8f69-b01cb2a39d51 fwd="100.9.117.185" dyno=web.1 connect=0ms service=92ms status=302 bytes=1006
2016-06-08T22:23:28.040594+00:00 heroku[router]: at=info method=GET path="/" host=masteryourmacros.herokuapp.com request_id=56ad519f-0c6b-4c94-a951-27561f2e0eca fwd="100.9.117.185" dyno=web.1 connect=1ms service=13ms status=500 bytes=1669
2016-06-08T22:23:43.314786+00:00 app[web.1]: Started POST "/users" for 100.9.117.185 at 2016-06-08 22:23:43 +0000
2016-06-08T22:23:43.375428+00:00 app[web.1]:    (5.9ms)  ROLLBACK
2016-06-08T22:23:43.348025+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Ie4dFW9KOjz3DW8ukwZtgtB8Z9mOzvoFcwH/FvBPhacNgK61Cy2MoWn1ju3MYHHbRPqnjMLRJCYexWA2uRQzmA==", "user"=>{"name"=>"Kathy wilkinson", "carbs_goal"=>"100", "fat_goal"=>"", "protein_goal"=>"", "email"=>"Wilkinson.Kathy.E@gmail.com", "password"=>"[FILTERED]"}, "commit"=>"Sign Up"}
2016-06-08T22:23:43.381067+00:00 app[web.1]:   Rendered layouts/_nav.html.erb (4.8ms)
2016-06-08T22:23:43.356446+00:00 app[web.1]:    (0.7ms)  BEGIN
2016-06-08T22:23:43.368537+00:00 app[web.1]:   User Exists (10.5ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'Wilkinson.Kathy.E@gmail.com' LIMIT 1
2016-06-08T22:23:43.345296+00:00 app[web.1]: Processing by UsersController#create as HTML
2016-06-08T22:23:43.380791+00:00 app[web.1]:   User Load (3.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 7]]
2016-06-08T22:23:43.397602+00:00 app[web.1]: Completed 200 OK in 46ms (Views: 18.1ms | ActiveRecord: 20.8ms)
2016-06-08T22:23:43.395311+00:00 app[web.1]:   Rendered users/new.html.erb within layouts/application (19.2ms)
2016-06-08T22:23:43.401817+00:00 heroku[router]: at=info method=POST path="/users" host=masteryourmacros.herokuapp.com request_id=0db0d29d-3402-4c28-955f-f9982c7284dd fwd="100.9.117.185" dyno=web.1 connect=0ms service=90ms status=200 bytes=4243
2016-06-08T22:23:53.398812+00:00 app[web.1]:    (0.9ms)  BEGIN
2016-06-08T22:23:53.312810+00:00 app[web.1]: Started POST "/users" for 100.9.117.185 at 2016-06-08 22:23:53 +0000
2016-06-08T22:23:53.315278+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"/1Mk16xrg+vrB0DIQv6FWMRDFeLjsXgFkWwMhmCvgHrTPZd3yAw1dnX/oQsdmJkBUMXVt6+upib8qJOmKfQ2RQ==", "user"=>{"name"=>"Kathy wilkinson", "carbs_goal"=>"100", "fat_goal"=>"", "protein_goal"=>"", "email"=>"Wilkinson.Kathy.E@gmail.com", "password"=>"[FILTERED]"}, "commit"=>"Sign Up"}
2016-06-08T22:23:53.402949+00:00 app[web.1]:    (0.7ms)  ROLLBACK
2016-06-08T22:23:53.405627+00:00 app[web.1]:   Rendered layouts/_nav.html.erb (1.8ms)
2016-06-08T22:23:53.416509+00:00 app[web.1]:   Rendered users/new.html.erb within layouts/application (12.8ms)
2016-06-08T22:23:53.401075+00:00 app[web.1]:   User Exists (1.0ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'Wilkinson.Kathy.E@gmail.com' LIMIT 1
2016-06-08T22:23:53.417427+00:00 app[web.1]: Completed 200 OK in 102ms (Views: 13.2ms | ActiveRecord: 3.3ms)
2016-06-08T22:23:53.404812+00:00 app[web.1]:   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 7]]
2016-06-08T22:23:53.315100+00:00 app[web.1]: Processing by UsersController#create as HTML
2016-06-08T22:23:53.422080+00:00 heroku[router]: at=info method=POST path="/users" host=masteryourmacros.herokuapp.com request_id=dc5a2360-96f0-4fa5-a200-6558850b9c42 fwd="100.9.117.185" dyno=web.1 connect=0ms service=112ms status=200 bytes=4163
2016-06-08T22:23:53.536077+00:00 heroku[router]: at=info method=GET path="/assets/application-395374b99eca8215aa0c2a82a365cb16fbed444a55e71217b4b88290955d3156.css" host=masteryourmacros.herokuapp.com request_id=e111b308-abbb-47e7-b213-4681e13ad202 fwd="100.9.117.185" dyno=web.1 connect=0ms service=1ms status=304 bytes=48
2016-06-08T22:23:53.643519+00:00 heroku[router]: at=info method=GET path="/logo.png" host=masteryourmacros.herokuapp.com request_id=ca2a16aa-5861-4007-8c94-164c518e8d1d fwd="100.9.117.185" dyno=web.1 connect=0ms service=5ms status=304 bytes=48
2016-06-08T22:23:53.661826+00:00 heroku[router]: at=info method=GET path="/assets/application-47feac84829615907e7d9e9e4f934dda30e6ccdaf38f2cd263a63797d486050d.js" host=masteryourmacros.herokuapp.com request_id=52d9ec6b-4a5f-49f8-96b4-3c9344151984 fwd="100.9.117.185" dyno=web.1 connect=0ms service=5ms status=304 bytes=48
2016-06-08T22:24:25.991051+00:00 heroku[router]: at=info method=POST path="/users" host=masteryourmacros.herokuapp.com request_id=33d3574b-4e28-4b44-82f9-640fc4b760ae fwd="100.9.117.185" dyno=web.1 connect=0ms service=40ms status=200 bytes=4290
2016-06-08T22:24:25.957049+00:00 app[web.1]: Started POST "/users" for 100.9.117.185 at 2016-06-08 22:24:25 +0000
2016-06-08T22:24:25.965139+00:00 app[web.1]: Processing by UsersController#create as HTML
2016-06-08T22:24:25.965467+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"SBl0I4EvmXQ3aFh9hXnIXbk4kw2WmEQBOp9dMiL/E3Rkd8eD5Ugv6amQub7aH9QELb5TWNqHmiJXW8ISa6SlSw==", "user"=>{"name"=>"Kathy wilkinson", "carbs_goal"=>"100", "fat_goal"=>"100", "protein_goal"=>"200", "email"=>"Wilkinson.Kathy.E@gmail.com", "password"=>"[FILTERED]"}, "commit"=>"Sign Up"}
2016-06-08T22:24:25.972132+00:00 app[web.1]:    (4.8ms)  BEGIN
2016-06-08T22:24:25.975260+00:00 app[web.1]:   User Exists (1.1ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'Wilkinson.Kathy.E@gmail.com' LIMIT 1
2016-06-08T22:24:25.977060+00:00 app[web.1]:    (0.7ms)  ROLLBACK
2016-06-08T22:24:25.978902+00:00 app[web.1]:   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 7]]
2016-06-08T22:24:25.979779+00:00 app[web.1]:   Rendered layouts/_nav.html.erb (1.9ms)
2016-06-08T22:24:25.985610+00:00 app[web.1]:   Rendered users/new.html.erb within layouts/application (7.8ms)
2016-06-08T22:24:25.986495+00:00 app[web.1]: Completed 200 OK in 21ms (Views: 8.2ms | ActiveRecord: 7.3ms)
2016-06-08T22:24:40.626522+00:00 app[web.1]: Started POST "/users" for 100.9.117.185 at 2016-06-08 22:24:40 +0000
2016-06-08T22:24:40.628284+00:00 app[web.1]: Processing by UsersController#create as HTML
2016-06-08T22:24:40.628396+00:00 app[web.1]:   Parameters: {"utf8"=>"✓", "authenticity_token"=>"LNI19BU2UhtqAuQzrHt2fddANRjjj0aJUEHIX6FHJIcAvIZUcVHkhvT6BfDzHWokQ8b1Ta+QmKo9hVd/6BySuA==", "user"=>{"name"=>"Kathy wilkinson", "carbs_goal"=>"100", "fat_goal"=>"100", "protein_goal"=>"200", "email"=>"Wilkinson.Kathy.E@gmail.com", "password"=>"[FILTERED]"}, "commit"=>"Sign Up"}
2016-06-08T22:24:40.708299+00:00 app[web.1]:    (0.9ms)  BEGIN
2016-06-08T22:24:40.709939+00:00 app[web.1]:   User Exists (0.9ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'Wilkinson.Kathy.E@gmail.com' LIMIT 1
2016-06-08T22:24:40.712955+00:00 app[web.1]:   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 7]]
2016-06-08T22:24:40.720837+00:00 app[web.1]: Completed 200 OK in 92ms (Views: 8.4ms | ActiveRecord: 3.2ms)
2016-06-08T22:24:40.719806+00:00 app[web.1]:   Rendered users/new.html.erb within layouts/application (7.9ms)
2016-06-08T22:24:40.713810+00:00 app[web.1]:   Rendered layouts/_nav.html.erb (1.8ms)
2016-06-08T22:24:40.711285+00:00 app[web.1]:    (0.6ms)  ROLLBACK
2016-06-08T22:24:40.728708+00:00 heroku[router]: at=info method=POST path="/users" host=masteryourmacros.herokuapp.com request_id=edbc59d2-041d-4217-931b-19dbbfdd4fcb fwd="100.9.117.185" dyno=web.1 connect=0ms service=104ms status=200 bytes=4169
2016-06-08T22:24:40.903013+00:00 heroku[router]: at=info method=GET path="/assets/application-395374b99eca8215aa0c2a82a365cb16fbed444a55e71217b4b88290955d3156.css" host=masteryourmacros.herokuapp.com request_id=8ccdf434-78bb-4c83-b5dd-5b112d79d943 fwd="100.9.117.185" dyno=web.1 connect=0ms service=1ms status=304 bytes=48
2016-06-08T22:24:40.997488+00:00 heroku[router]: at=info method=GET path="/logo.png" host=masteryourmacros.herokuapp.com request_id=3d1f4fd7-e531-4ce9-9017-d05747814e7f fwd="100.9.117.185" dyno=web.1 connect=0ms service=1ms status=304 bytes=48
2016-06-08T22:24:48.047967+00:00 app[web.1]: Started GET "/" for 100.9.117.185 at 2016-06-08 22:24:48 +0000
2016-06-08T22:24:48.053257+00:00 app[web.1]: Completed 500 Internal Server Error in 3ms (ActiveRecord: 1.5ms)
2016-06-08T22:24:48.052825+00:00 app[web.1]:   Food Load (0.7ms)  SELECT "foods".* FROM "foods" WHERE "foods"."user_id" = $1  [["user_id", 7]]
2016-06-08T22:24:48.094063+00:00 heroku[router]: at=info method=GET path="/" host=masteryourmacros.herokuapp.com request_id=b4bf4297-0545-43eb-b52f-fc144b654b3f fwd="100.9.117.185" dyno=web.1 connect=1ms service=8ms status=500 bytes=1669
2016-06-08T22:24:48.051349+00:00 app[web.1]:   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 7]]
2016-06-08T22:24:48.049798+00:00 app[web.1]: Processing by StaticpagesController#index as HTML
2016-06-08T22:24:48.053926+00:00 app[web.1]: 
2016-06-08T22:24:48.053941+00:00 app[web.1]: TypeError (nil can't be coerced into Fixnum):
2016-06-08T22:24:48.053942+00:00 app[web.1]:   app/controllers/staticpages_controller.rb:13:in `/'
2016-06-08T22:24:48.053943+00:00 app[web.1]:   app/controllers/staticpages_controller.rb:13:in `index'
2016-06-08T22:24:48.053943+00:00 app[web.1]: 
2016-06-08T22:24:48.053944+00:00 app[web.1]: 
2016-06-08T22:24:53.326002+00:00 heroku[router]: at=info method=GET path="/" host=masteryourmacros.herokuapp.com request_id=7e244f12-a6f9-4a7f-97f7-6b1b85bb5c95 fwd="100.9.117.185" dyno=web.1 connect=0ms service=12ms status=500 bytes=1669
2016-06-08T22:24:53.284415+00:00 app[web.1]:   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 7]]
2016-06-08T22:24:53.278721+00:00 app[web.1]: Started GET "/" for 100.9.117.185 at 2016-06-08 22:24:53 +0000
2016-06-08T22:24:53.282681+00:00 app[web.1]: Processing by StaticpagesController#index as HTML
2016-06-08T22:24:53.287870+00:00 app[web.1]: TypeError (nil can't be coerced into Fixnum):
2016-06-08T22:24:53.286216+00:00 app[web.1]:   Food Load (0.8ms)  SELECT "foods".* FROM "foods" WHERE "foods"."user_id" = $1  [["user_id", 7]]
2016-06-08T22:24:53.287871+00:00 app[web.1]:   app/controllers/staticpages_controller.rb:13:in `/'
2016-06-08T22:24:53.287873+00:00 app[web.1]: 
2016-06-08T22:24:53.286787+00:00 app[web.1]: Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.6ms)
2016-06-08T22:24:53.287855+00:00 app[web.1]: 
2016-06-08T22:24:53.287872+00:00 app[web.1]:   app/controllers/staticpages_controller.rb:13:in `index'
2016-06-08T22:24:53.287872+00:00 app[web.1]: 
2016-06-08T22:25:01.423094+00:00 app[web.1]:   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1  [["id", 7]]
2016-06-08T22:25:01.421375+00:00 app[web.1]: Processing by StaticpagesController#index as HTML
2016-06-08T22:25:01.426229+00:00 app[web.1]: TypeError (nil can't be coerced into Fixnum):
2016-06-08T22:25:01.425437+00:00 app[web.1]: Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.5ms)
2016-06-08T22:25:01.426231+00:00 app[web.1]:   app/controllers/staticpages_controller.rb:13:in `index'
2016-06-08T22:25:01.424731+00:00 app[web.1]:   Food Load (0.8ms)  SELECT "foods".* FROM "foods" WHERE "foods"."user_id" = $1  [["user_id", 7]]
2016-06-08T22:25:01.419645+00:00 app[web.1]: Started GET "/" for 100.9.117.185 at 2016-06-08 22:25:01 +0000
2016-06-08T22:25:01.426231+00:00 app[web.1]:   app/controllers/staticpages_controller.rb:13:in `/'
2016-06-08T22:25:01.426232+00:00 app[web.1]: 
2016-06-08T22:25:01.426222+00:00 app[web.1]: 
2016-06-08T22:25:01.426232+00:00 app[web.1]: 
2016-06-08T22:25:01.441752+00:00 heroku[router]: at=info method=GET path="/" host=masteryourmacros.herokuapp.com request_id=8aee0e63-b1cd-4d96-99a1-49d56b322552 fwd="100.9.117.185" dyno=web.1 connect=3ms service=17ms status=500 bytes=1669

**Comment by EARnagram** [comment]
I'm coming over to help!

**Comment by h4w5** [comment]
Time zones are so hard!!
